# Generated by Django 4.2.4 on 2024-02-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='Nothing', max_length=500),
            preserve_default=False,
        ),
    ]
